// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package repository

import (
	"context"
)

type Querier interface {
	GetUser(ctx context.Context, email string) (User, error)
	Registration(ctx context.Context, arg RegistrationParams) error
}

var _ Querier = (*Queries)(nil)
